In [22]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn import tree

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/alyanisaelsa/dataset/main/dataset.csv')
df

age         workclass  fnlwgt     education  education_num  \
0    32      Self-emp-inc   46807       HS-grad              9   
1    48  Self-emp-not-inc  317360     Bachelors             13   
2    30           Private  425627  Some-college             10   
3    34           Private   82623       HS-grad              9   
4    39           Private  140854       HS-grad              9   
5    28           Private  185061          11th              7   
6    54           Private  282680     Bachelors             13   
7    24           Private  137591  Some-college             10   
8    25           Private  198163       HS-grad              9   
9    25           Private  132749          11th              7   
10   48         Local-gov   31264  Some-college             10   
11   24           Private  399449     Bachelors             13   
12   31           Private   27494  Some-college             10   
13   47           Private  368561  Some-college             10   

        marital_status         occupation    relationship                race  \
0   Married-civ-spouse       Craft-repair         Husband               White   
1   Married-civ-spouse     Prof-specialty            Wife               White   
2        Never-married       Craft-repair  Other-relative               White   
3   Married-civ-spouse      Other-service         Husband               White   
4        Never-married     Prof-specialty   Not-in-family               White   
5        Never-married  Handlers-cleaners  Other-relative               White   
6        Never-married     Prof-specialty   Not-in-family               White   
7        Never-married              Sales       Own-child               White   
8        Never-married    Exec-managerial       Own-child               White   
9             Divorced      Other-service       Unmarried               White   
10  Married-civ-spouse    Exec-managerial            Wife               White   
11       Never-married              Sales       Own-child               White   
12  Married-civ-spouse              Sales         Husband  Asian-Pac-Islander   
13  Married-civ-spouse       Craft-repair         Husband               White   

       sex native_country income  
0     Male  United-States   >50K  
1   Female  United-States   >50K  
2     Male         Mexico  <=50K  
3     Male  United-States  <=50K  
4     Male  United-States  <=50K  
5     Male  United-States  <=50K  
6   Female  United-States  <=50K  
7     Male  United-States  <=50K  
8   Female  United-States  <=50K  
9   Female  United-States  <=50K  
10  Female  United-States   >50K  
11  Female  United-States  <=50K  
12    Male         Taiwan  <=50K  
13    Male  United-States   >50K

In [ ]:
columns = df.columns
df[columns] = df[columns].apply(lambda x: x.astype('category')) 
df[columns] = df[columns].apply(lambda x: x.cat.codes) 
df

age  workclass  fnlwgt  education  education_num  marital_status  \
0     5          2       2          2              1               1   
1     9          3      10          1              3               1   
2     3          1      13          3              2               2   
3     6          1       3          2              1               1   
4     7          1       6          2              1               2   
5     2          1       7          0              0               2   
6    10          1       9          1              3               2   
7     0          1       5          3              2               2   
8     1          1       8          2              1               2   
9     1          1       4          0              0               0   
10    9          0       1          3              2               1   
11    0          1      12          1              3               2   
12    4          1       0          3              2               1   
13    8          1      11          3              2               1   

    occupation  relationship  race  sex  native_country  income  
0            0             0     1    1               2       1  
1            4             5     1    0               2       1  
2            0             2     1    1               0       0  
3            3             0     1    1               2       0  
4            4             1     1    1               2       0  
5            2             2     1    1               2       0  
6            4             1     1    0               2       0  
7            5             3     1    1               2       0  
8            1             3     1    0               2       0  
9            3             4     1    0               2       0  
10           1             5     1    0               2       1  
11           5             3     1    0               2       0  
12           5             0     0    1               1       0  
13           0             0     1    1               2       1

In [ ]:
df_x = df.iloc[:, 0:11] #atribut
df_y = df.iloc[:,11] #kelas
df_y

0     1
1     1
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    1
11    0
12    0
13    1
Name: income, dtype: int8

In [ ]:
X = df_x.to_numpy()
y = df_y.to_numpy()

In [ ]:
gnb = GaussianNB()
model = gnb.fit(X, y) 

In [23]:
# 19, private, 406078, Some-college, 10, Never-married, Adm-clerical, Own-child, white, Female, United-States
x_test = [[2,1,14,3,2,2,6,3,1,0,2]]

y_pred = model.predict(x_test)
y_pred

array([0], dtype=int8)

In [24]:
# 52, self-emp-inc, 100506, Some-college, 10, Married-civ-spouse, Sales, Husband, white, Male, United-States
x_test = [[11,2,15,3,2,1,5,0,1,1,2]]

y_pred = model.predict(x_test)
y_pred

array([1], dtype=int8)

In [30]:
# 52, private, 29658, HS-grad, 9, Married-civ-spouse, Adm-clerical, Husband, white, Male, United-States
x_test = [[11,1,16,2,1,1,6,0,1,1,2]]

y_pred = model.predict(x_test)
y_pred

array([1], dtype=int8)

In [31]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, y)

In [32]:
# 19, private, 406078, Some-college, 10, Never-married, Adm-clerical, Own-child, white, Female, United-States
x_test = [[2,1,14,3,2,2,6,3,1,0,2]]

y_pred = model.predict(x_test)
y_pred

array([0], dtype=int8)

In [33]:
# 52, self-emp-inc, 100506, Some-college, 10, Married-civ-spouse, Sales, Husband, white, Male, United-States
x_test = [[11,2,15,3,2,1,5,0,1,1,2]]

y_pred = model.predict(x_test)
y_pred

array([1], dtype=int8)

In [34]:
# 52, private, 29658, HS-grad, 9, Married-civ-spouse, Adm-clerical, Husband, white, Male, United-States
x_test = [[11,1,16,2,1,1,6,0,1,1,2]]

y_pred = model.predict(x_test)
y_pred

array([1], dtype=int8)